name = "Moreau"
uuid = "c8b129f6-74e5-4f0d-b2d8-2ea10d91a548"
version = "0.1.0"
repo = "https://github.com/moreau-project/Moreau.jl"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[extensions]
MoreauCUDAExt = "CUDA"
MoreauChainRulesExt = "ChainRulesCore"

[compat]
Artifacts = "1"
CUDA = "5"
ChainRulesCore = "1"
JuMP = "1.30.0"
LazyArtifacts = "1"
Libdl = "1"
LinearAlgebra = "1"
MathOptInterface = "1"
SparseArrays = "1.12.0"
TOML = "1"
Test = "1"
julia = "1.12"

[extras]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[targets]
test = ["Test", "JuMP", "TOML"]
